openapi: 3.0.3
info:
  title: Popper
  description: Backend spec for popper app
  version: 0.3.0

servers:
  - url: 'http://0.0.0.0:8008'
  - url: 'https://api.remcoil.webtm.ru'
paths:

  /v2/product:
    get:
      tags:
        - product
      responses:
        '200':
          description: Список всех изделий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfProductsV2'

  /v2/product/{id}:
    get:
      tags:
        - product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Данные об изделии
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductV2'
        '404':
          description: Изделие не найдено
        '400':
          description: Bad request

  /v2/product/{id}/deactivate:
    patch:
      tags:
        - product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Изделие отмечено как бракованное
        '404':
          description: Изделие не найдено
        '400':
          description: Bad request

  /v2/batch/{batch_id}/product:
    get:
      tags:
        - product
      parameters:
        - in: path
          name: batch_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Список изделий одной партии
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfProductsV2'
        '400':
          description: Bad request

  /v2/specification:
    get:
      tags:
        - specification
      responses:
        '200':
          description: Список ТЗ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfSpecificationResponsesV2'

    put:
      tags:
        - specification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecificationPutRequestV2'
      responses:
        '200':
          description: ТЗ обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecificationResponseV2'
        '400':
          description: Bad request

    post:
      tags:
        - specification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecificationPostRequestV2'
      responses:
        '200':
          description: ТЗ создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecificationResponseV2'

  /v2/specification/{id}:
    get:
      tags:
        - specification
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация о ТЗ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecificationResponseV2'
        '404':
          description: Not found

    delete:
      tags:
        - specification
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация о ТЗ удалена
        '400':
          description: Bad request


  /v2/batch:
    get:
      tags:
        - batch
      responses:
        '200':
          description: Список партий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfBatchesV2'


  /v2/batch/{id}/codes:
    get:
      tags:
        - batch
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: QR коды для изделий одной партии

  /v2/action:
    get:
      tags:
        - action
      responses:
        '200':
          description: Список операций
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfActionsV2'

    post:
      security:
        - bearerAuth: [ ]
      tags:
        - action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRequestV2'
      responses:
        '400':
          description: Bad request
        '200':
          description: Операция создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionV2'
    put:
      tags:
        - action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionV2'
      responses:
        '200':
          description: Action update
        '400':
          description: Bad request

  /v2/action/batch:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - batch_action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchActionRequestV2'
      responses:
        '400':
          description: Bad request
        '200':
          description: Операции созданы
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfActionsV2'

  /v2/action/product/{product_id}:
    get:
      tags:
        - action
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Список операций для одного изделия
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfActionsV2'

  /v2/action/{id}:
    delete:
      tags:
        - action
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация об операции удалена

  /v2/control_action:
    get:
      tags:
        - control_action
      responses:
        '200':
          description: Список операций контроля
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfControlActionsV2'

    post:
      security:
        - bearerAuth: [ ]
      tags:
        - control_action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ControlActionRequestV2'
      responses:
        '400':
          description: Bad request
        '200':
          description: Операция создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ControlActionV2'
    put:
      tags:
        - control_action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ControlActionV2'
      responses:
        '200':
          description: Action update
        '400':
          description: Bad request

  /v2/control_action/{id}:
    delete:
      tags:
        - control_action
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация об операции удалена

  /v2/operation_type:
    post:
      tags:
        - operation_type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationTypeV2'
      responses:
        '200':
          description: Тип сохранен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTypeV2'

    put:
      tags:
        - operation_type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationTypeV2'
      responses:
        '200':
          description: Информация о типе обновлена

  /v2/operation_type/specification/{id}:
    get:
      tags:
        - operation_type
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация о типах операций ТЗ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfOperationTypesV2'

  /v2/operation_type/{id}:
    delete:
      tags:
        - operation_type
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация о типе удалена


  /v2/kit:
    get:
      tags:
        - kit
      responses:
        '200':
          description: Список всех наборов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfKitsV2'

    post:
      tags:
        - kit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KitV2'
      responses:
        '200':
          description: Набор сохранен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KitV2'

    put:
      tags:
        - kit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KitV2'
      responses:
        '200':
          description: Информация о наборе обновлена

  /v2/kit/{id}/progress:
    get:
      tags:
        - kit
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '204':
          description: No content
        '200':
          description: Информация о наборе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KitProgressV2'

  /v2/kit/{id}:
    get:
      tags:
        - kit
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '204':
          description: No content
        '200':
          description: Информация о наборе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KitV2'

    delete:
      tags:
        - kit
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Информация о наборе удалена

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ActionV2:
      properties:
        id:
          type: number
        done_time:
          type: string
          format: YYYY-MM-DDTHH:MM:SS
          example: "2022-12-25T14:30:01"
        repair:
          type: boolean
          default: false
        operation_type:
          type: number
        employee_id:
          type: number
        product_id:
          type: number

    BatchActionRequestV2:
      properties:
        done_time:
          type: string
          format: YYYY-MM-DDTHH:MM:SS
          example: "2022-12-25T14:30:01"
        repair:
          type: boolean
          default: false
        operation_type:
          type: number
        batch_id:
          type: number

    ActionRequestV2:
      properties:
        done_time:
          type: string
          format: YYYY-MM-DDTHH:MM:SS
          example: "2022-12-25T14:30:01"
        repair:
          type: boolean
          default: false
        operation_type:
          type: number
        product_id:
          type: number

    ProductV2:
      properties:
        id:
          type: number
        product_number:
          type: integer
        active:
          type: boolean
        batch_id:
          type: number

    BatchV2:
      properties:
        id:
          type: number
        batch_number:
          type: string
        kit_id:
          type: number

    BatchProgressV2:
      properties:
        id:
          type: number
        batch_number:
          type: number
        operations_progress:
          type: object
          additionalProperties:
            type: integer
        control_progress:
          type: object
          additionalProperties:
            type: integer
        locked_quantity:
          type: integer
        defected_quantity:
          type: integer

    KitProgressV2:
      properties:
        id:
          type: number
        kit_number:
          type: string
        batches_quantity:
          type: integer
        operation_types:
          type: array
          items:
            $ref: '#/components/schemas/OperationTypeV2'
        batches_progress:
          type: array
          items:
            $ref: '#/components/schemas/BatchProgressV2'


    KitV2:
      properties:
        id:
          type: number
        kit_number:
          type: string
        batches_quantity:
          type: integer
        batch_size:
          type: integer
        specification_id:
          type: number

    SpecificationPostRequestV2:
      properties:
        id:
          type: number
        specification_title:
          type: string
        product_type:
          type: string
        tested_percentage:
          type: integer
        operation_types:
          type: array
          items:
            $ref: '#/components/schemas/OperationTypeRequestV2'

    SpecificationPutRequestV2:
      properties:
        id:
          type: number
        specification_title:
          type: string
        product_type:
          type: string
        tested_percentage:
          type: integer
        operation_types:
          type: array
          items:
            $ref: '#/components/schemas/OperationTypeV2'

    SpecificationResponseV2:
      properties:
        id:
          type: number
        specification_title:
          type: string
        product_type:
          type: string
        tested_percentage:
          type: integer
        kit_quantity:
          type: integer
        operation_types:
          type: array
          items:
            $ref: '#/components/schemas/OperationTypeV2'

    OperationTypeV2:
      properties:
        id:
          type: number
        type:
          type: string
        sequence_number:
          type: integer
        specification_id:
          type: number

    OperationTypeRequestV2:
      properties:
        type:
          type: string
        sequence_number:
          type: integer

    ControlActionRequestV2:
      properties:
        done_time:
          type: string
          format: YYYY-MM-DDTHH:MM:SS
          example: "2022-12-25T14:30:01"
        successful:
          type: boolean
        control_type:
          type: string
        comment:
          type: string
        operation_type:
          type: number
        product_id:
          type: number

    ControlActionV2:
      properties:
        id:
          type: number
        done_time:
          type: string
          format: YYYY-MM-DDTHH:MM:SS
          example: "2022-12-25T14:30:01"
        successful:
          type: boolean
        control_type:
          type: string
        comment:
          type: string
        operation_type:
          type: number
        employee_id:
          type: number
        product_id:
          type: number

    ListOfActionsV2:
      type: array
      items:
        $ref: '#/components/schemas/ActionV2'

    ListOfControlActionsV2:
      type: array
      items:
        $ref: '#/components/schemas/ControlActionV2'

    ListOfOperationTypesV2:
      type: array
      items:
        $ref: '#/components/schemas/OperationTypeV2'

    ListOfSpecificationResponsesV2:
      type: array
      items:
        $ref: '#/components/schemas/SpecificationResponseV2'

    ListOfBatchesV2:
      type: array
      items:
        $ref: '#/components/schemas/BatchV2'

    ListOfKitsV2:
      type: array
      items:
        $ref: '#/components/schemas/KitV2'

    ListOfProductsV2:
      type: array
      items:
        $ref: '#/components/schemas/ProductV2'
