version: "3.6"

services:
  popper:
    container_name: popper_main_service
    image: pampero.registry.jetbrains.space/p/popper/popper/popper_server:0.3.0-dev-15
    environment:
      PORT: ${POPPER_INNER_PORT}
      HOST: ${HOST}
      JDBC_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      JDBC_DATABASE_USERNAME: ${POSTGRES_USER}
      JDBC_DATABASE_URL: ${POSTGRES_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TIME: ${JWT_TIME}
    depends_on:
      - database
    ports:
      - ${POPPER_EXTERNAL_PORT}:${POPPER_INNER_PORT}

  database:
    image: postgres:11
    container_name: popper_database
    volumes:
      - popper_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  popper_db: